[prop]
id = "asl"
name = "AndroidSubSystem4Linux"
version = "1.0.7"
versionCode = 1765648726660
author = "LIghtJUNction"
description = "Run GUN/Linux on android , powered by rurima & build-system: kam."
updateJson = "https://github.com/KernelSU-Modules-Repo/releases/latest/download/asl.zip"
metamodule = false

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = "https://github.com/KernelSU-Modules-Repo/asl"
readme = "https://github.com/KernelSU-Modules-Repo/blob/main/README.md"
readme_file = "README.md"
changelog = "https://github.com/KernelSU-Modules-Repo/blob/main/CHANGELOG.md"
changelog_file = "CHANGELOG.md"
screenshots = ["Screenshot_2025-12-08-01-18-25-97_84d3000e3f4017145260f7618db1d683.jpg"]
categories = ["tools"]
keywords = [
    "ka",
    "rurima",
]
maintainers = [
    "Moe-hacker",
    "Lin1328",
]
repository = "https://github.com/KernelSU-Modules-Repo/asl"
documentation = ""
issues = "https://github.com/KernelSU-Modules-Repo/asl/issues"
funding = "https://github.com/sponsors/LIghtJUNction"
support = ""
donate = ""
cover = ""
icon = "icon.png"
devices = []
arch = ["arm64-v8a"]
require = []
antifeatures = []
max_num = 0
min_api = 21
max_api = 35
verified = false
features = []

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "kam"

[kam.build]
target_dir = "dist"
output_file = "{{id}}"
hooks_dir = "hooks"

[kam.tmpl.variables.repository]
var_type = "string"
required = false
default = ""

[kam.workspace]
members = ["."]

[tool]
